spring:
  application:
    name: hhplus
  profiles:
    active: local, scheduler
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

---
spring:
  config:
    activate:
      on-profile: local, test

  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema.sql
        - classpath:sql/data.sql

  jpa:
    defer-datasource-initialization: true

jwt:
  secret: uLzJXp4n5z9J9fV4p8VJdRhBqBv9c8r+O7dnYGfH1V4=
  expiration-minutes: 5

---
spring:
  config:
    activate:
      on-profile: performance

  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: concurrency-test

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema.sql
        - classpath:sql/data.sql

  jpa:
    defer-datasource-initialization: true

server:
  port: 8080

jwt:
  secret: uLzJXp4n5z9J9fV4p8VJdRhBqBv9c8r+O7dnYGfH1V4=
  expiration-minutes: 5
