openapi: 3.0.1
info:
  title: concert reservation server
  description: API Documents
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/payments:
    post:
      tags:
      - 결제
      summary: 포인트 결제 요청 API
      description: 포인트 결제 시 사용되는 API
      operationId: 포인트 결제
      parameters:
      - name: EntryQueueToken
        in: header
        description: 대기열 토큰
        required: true
        schema:
          type: string
        example: token
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-payments-263291135"
              examples:
                포인트 결제:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "totalPrice" : 1000,
                        "reservationCount" : 1
                      }
                    }
  /api/reservations:
    post:
      tags:
      - 예약
      summary: 예약 생성 요청 API
      description: 좌석을 예약할 때 사용되는 API 입니다.
      operationId: 예약 생성
      parameters:
      - name: EntryQueueToken
        in: header
        description: 대기열 토큰
        required: true
        schema:
          type: string
        example: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-reservations-1797044994"
            examples:
              예약 생성 - 잘못된 요청:
                value: |-
                  {
                    "date" : "2025-08-14",
                    "seat" : -1
                  }
              예약 생성:
                value: |-
                  {
                    "date" : "2025-08-14",
                    "seat" : 1
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-reservations2069535653"
              examples:
                예약 생성 - 잘못된 요청:
                  value: |-
                    {
                      "code" : 400,
                      "message" : "invalid request value.",
                      "result" : {
                        "errors" : [ {
                          "field" : "seat",
                          "value" : -1
                        } ]
                      }
                    }
                예약 생성:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "userId" : "2785db52-57db-4e14-abd0-971bf9533e6c",
                        "concertSeatId" : 1,
                        "concertDate" : "2025-08-14",
                        "reservedAt" : "2025-08-13T09:21:24.085296",
                        "expiresAt" : "2025-08-13T09:27:24.085299"
                      }
                    }
  /api/queue/entry-token:
    post:
      tags:
      - 대기열 토큰
      summary: 대기열 토큰 발급 API
      description: 대기열 토큰 발급 시 사용되는 API
      operationId: 대기열 토큰
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-queue-entry-token-200765834"
            examples:
              대기열 토큰:
                value: |-
                  {
                    "userId" : "deee7f1f-073d-4052-8ae8-9405897f79a5"
                  }
              대기열 토큰 - 잘못된 요청:
                value: |-
                  {
                    "userId" : ""
                  }
      responses:
        "200":
          description: "200"
          headers:
            EntryQueueToken:
              description: 대기열 토큰 값
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-queue-entry-token1812758081"
              examples:
                대기열 토큰:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
                대기열 토큰 - 잘못된 요청:
                  value: |-
                    {
                      "code" : 400,
                      "message" : "invalid request value.",
                      "result" : {
                        "errors" : [ {
                          "field" : "userId",
                          "value" : ""
                        } ]
                      }
                    }
  /api/users/{id}/points:
    get:
      tags:
      - 유저 포인트
      summary: 유저 포인트 조회 API
      description: 유저 포인트 조회 시 사용되는 API
      operationId: 유저 포인트 조회
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: EntryQueueToken
        in: header
        description: 대기열 토큰
        required: true
        schema:
          type: string
        example: token
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-users-id-points1371282021"
              examples:
                유저 포인트 조회:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "userId" : "320c5aeb-e9d0-4f82-9951-d8bf1eb5a3e6",
                        "balance" : 1000
                      }
                    }
  /api/concerts/{id}/reservations/available-dates:
    get:
      tags:
      - 콘서트
      summary: 콘서트 예약 가능 날짜 조회 API
      description: 콘서트 예약 가능 날짜를 조회할 때 사용하는 API
      operationId: 콘서트 예약 가능 날짜 조회
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: EntryQueueToken
        in: header
        description: 대기열 토큰
        required: true
        schema:
          type: string
        example: token
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-concerts-id-reservations-available-dates2111023121"
              examples:
                콘서트 예약 가능 날짜 조회:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "dates" : [ "2025-08-13", "2025-08-13" ]
                      }
                    }
  /api/concerts/{id}/reservations/available-seats:
    get:
      tags:
      - 콘서트
      summary: 콘서트 예약 가능 좌석 조회 API
      description: 콘서트 예약 가능 좌석을 조회할 때 사용하는 API
      operationId: 콘서트 예약 가능 좌석 조회
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: date
        in: query
        description: 좌석 조회 날짜
        required: true
        schema:
          type: string
      - name: EntryQueueToken
        in: header
        description: 대기열 토큰
        required: true
        schema:
          type: string
        example: token
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-concerts-id-reservations-available-seats-1415072009"
              examples:
                콘서트 예약 가능 좌석 조회:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "seats" : [ {
                          "id" : 1,
                          "number" : 1,
                          "price" : 1000
                        }, {
                          "id" : 2,
                          "number" : 2,
                          "price" : 3000
                        } ]
                      }
                    }
  /api/users/{id}/points/charge:
    post:
      tags:
      - 유저 포인트
      summary: 유저 포인트 충전 API
      description: 유저 포인트 충전 시 사용되는 API
      operationId: 유저 포인트 충전
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: EntryQueueToken
        in: header
        description: 대기열 토큰
        required: true
        schema:
          type: string
        example: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-users-id-points-charge-326542580"
            examples:
              유저 포인트 충전 - 잘못된 요청:
                value: |-
                  {
                    "amount" : -1
                  }
              유저 포인트 충전:
                value: |-
                  {
                    "amount" : 1000
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-users-id-points-charge736669744"
              examples:
                유저 포인트 충전 - 잘못된 요청:
                  value: |-
                    {
                      "code" : 400,
                      "message" : "invalid request value.",
                      "result" : {
                        "errors" : [ {
                          "field" : "amount",
                          "value" : -1
                        } ]
                      }
                    }
                유저 포인트 충전:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : 2000
                    }
components:
  schemas:
    api-concerts-id-reservations-available-seats-1415072009:
      type: object
      properties:
        result:
          type: object
          properties:
            seats:
              type: array
              description: 예약 가능 좌석 리스트
              items:
                type: object
                properties:
                  number:
                    type: number
                    description: 좌석 번호
                  price:
                    type: number
                    description: 좌석 가격
                  id:
                    type: number
                    description: 좌석 식별자
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-concerts-id-reservations-available-dates2111023121:
      type: object
      properties:
        result:
          type: object
          properties:
            dates:
              type: array
              description: 예약 가능 날짜 리스트
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-users-id-points-charge-326542580:
      type: object
      properties:
        amount:
          type: number
          description: 포인트 충전 금액
    api-users-id-points-charge736669744:
      type: object
      properties:
        result:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: 잘못 요청한 필드 이름
                  value:
                    type: number
                    description: 잘못 요청한 필드 값
          description: 유저 식별자
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-users-id-points1371282021:
      type: object
      properties:
        result:
          type: object
          properties:
            balance:
              type: number
              description: 포인트 잔액
            userId:
              type: string
              description: 유저 식별자
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-queue-entry-token1812758081:
      type: object
      properties:
        result:
          type: object
          properties:
            errors:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: 잘못 요청한 필드 이름
                  value:
                    type: string
                    description: 잘못 요청한 필드 값
        code:
          type: number
          description: 에러 코드
        message:
          type: string
          description: 에러 메시지
    api-reservations-1797044994:
      type: object
      properties:
        seat:
          type: number
          description: 좌석
        date:
          type: string
          description: 예약 일자
    api-queue-entry-token-200765834:
      type: object
      properties:
        userId:
          type: string
          description: 존재하지 않는 사용자 ID
    api-payments-263291135:
      type: object
      properties:
        result:
          type: object
          properties:
            totalPrice:
              type: number
              description: 가격
            reservationCount:
              type: number
              description: 예약 건수
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-reservations2069535653:
      type: object
      properties:
        result:
          type: object
          properties:
            concertDate:
              type: string
              description: 콘서트 날짜
            concertSeatId:
              type: number
              description: 콘서트 좌석 식별자
            reservedAt:
              type: string
              description: 예약 일자
            userId:
              type: string
              description: 유저 식별자
            expiresAt:
              type: string
              description: 예약 만료 일자
            errors:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: 잘못 요청한 필드 이름
                  value:
                    type: number
                    description: 잘못 요청한 필드 값
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
